
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: indigecomms_development

test:
  <<: *default
  database: indigecomms_test

production:
  <<: *default
  database: indigecomms_production
